project:
  title: "Slides"
  type: website
  output-dir: docs

format:
  html:
    theme: none
    css: static/top-page.css
  revealjs:
    theme: static/theme.css
    scrollable: true
    history: false
    slide-number: c/t
    code-line-numbers: false
    auto-stretch: false
